name: Publish

on:
    push:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: ^8.1.1
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'pnpm'
                  registry-url: 'https://npm.pkg.github.com'

            # NOTE: use organization build bot token to download dependencies across entire org
            - run: pnpm config set "//npm.pkg.github.com/:_authToken" "${{ secrets.GIT_BUILDBOT_TOKEN }}"
            - run: pnpm install
            - run: pnpm lint

            - uses: EndBug/version-check@v2
              id: check
              with:
                  diff-search: true
                  token: ${{ secrets.GITHUB_TOKEN }}

            - run: 'echo "New ${{ steps.check.outputs.type }} version changed to ${{ steps.check.outputs.version }}"'
              if: steps.check.outputs.changed == 'true'

            - run: 'echo "No version change detected, skipping publish."'
              if: steps.check.outputs.changed != 'true'

            # NOTE: now use the built-in GitHub Actions token because we're publishing to this repository's packages
            - run: pnpm config set "//npm.pkg.github.com/:_authToken" "${{ secrets.GITHUB_TOKEN }}"

            # only publish if the package.json version has changed
            - run: pnpm publish
              if: steps.check.outputs.changed == 'true'
